name: "Build the docker image and scan it"
description:  build docker image and scan it

inputs:
  # -- Docker image -- #
  image:
    description: "Name of the image"
    required: true
  tag:
    description: "How to tag the image"
    required: true
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  known_hosts:
    description: known_hosts to use for the CI
    default: ""
    required: false
  # -- Docker registry -- #

runs:
  using: "composite"
  steps:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ inputs.image }}:${{ inputs.tag }}
        context: .
