name: "Build the docker image and scan it"
description:  build docker image and scan it

inputs:
  # -- Docker image -- #
  image:
    description: "Name of the image"
    required: true
  tag:
    description: "How to tag the image"
    required: true
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  known_hosts:
    description: known_hosts to use for the CI
    default: ""
    required: false
  # -- Docker registry -- #

runs:
  using: "composite"
  steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh-key }}
        name: id_rsa # optional
        known_hosts: ${{ inputs.known_hosts }}
    - name: Build image with tag
      env:
        DOCKER_BUILDKIT: "1"
      run: docker buildx build -t ${{ inputs.image }}:${{ inputs.tag }} --ssh default=$SSH_AUTH_SOCK .
      shell: bash