name: "Build the docker image and scan it"
description:  build docker image and scan it

inputs:
  # -- Docker image -- #
  image:
    description: "Name of the image"
    required: true
  tag:
    description: "How to tag the image"
    required: true
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  known_hosts:
    description: known_hosts to use for the CI
    default: ""
    required: false
  # -- Docker registry -- #

runs:
  using: "composite"
  steps:
    - name: Build image with tag
      run: docker build -t ${{ inputs.image }}:${{ inputs.tag }} . --build-arg SSH_KEY="${{ inputs.ssh-key }}"
      shell: bash