name: "Security in Elixir projects"
description:  Check retired deps + security issues in deps and in code

inputs:
  # -- Run steps -- #
  run-hex-audit:
    description: Run Hex Audit
    default: "true"
  run-deps-audit:
    description: Run Deps Audit
    default: "true"
  run-sobelow:
    description: Run Sobelow
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Check retired dependencies
      run: mix hex.audit
      shell: bash
      if: ${{ inputs.run-hex-audit != "false" }}
    
    - name: Check security issues in Deps
      run: mix deps.audit
      shell: bash
      if: ${{ inputs.run-deps-audit != "false" }}

    - name: Check security issues in code
      run: mix sobelow --config
      shell: bash
      if: ${{ inputs.run-sobelow != "false" }}
