name: Run Elixir Project
description: Checks out the code and runs the test
inputs:
  elixir-version:
    required: true
    description: Elixir version to set up
  otp-version:
    required: true
    description: OTP version to set up
  ssh-key:
    description: SSH key to use for the CI
    required: true
  #################################################################
  # Everything below this line is optional.
  #################################################################
  check-credo:
    description: "Run credo"
    default: 'true'
    required: false
  check-sobelow:
    description: "Run sobelow"
    default: 'true'
    required: false
  check-deps-audit:
    description: "Run deps.audit"
    default: 'true'
    required: false
  check-doc-coverage:
    description: "Run doc coverage"
    default: 'true'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Elixir Project
      uses: myriad-sas/.github/.github/actions/elixir-setup@hub-security
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        ssh-key: ${{ inputs.ssh-key }}
    
    - name: Run linter
      run: mix credo
      shell: sh
      if: ${{ inputs.check-credo }} == 'true'

    - name: Run security scan on code
      run: mix sobelow --config
      shell: sh
      if: ${{ inputs.check-sobelow }} == 'true'

    - name: Run audit of dependencies
      run: mix hex.audit
      shell: sh
      if: ${{ inputs.check-deps-audit }} == 'true'

    - name: Run doc coverage
      run: mix doctor
      shell: sh
      if: ${{ inputs.check-doc-coverage }} == 'true'
