name: Run Elixir Project
description: Checks out the code and runs the test
inputs:
  elixir-version:
    required: true
    description: Elixir version to set up
  otp-version:
    required: true
    description: OTP version to set up
  ssh-key:
    description: SSH key to use for the CI
    required: true
  #################################################################
  # Everything below this line is optional.
  #################################################################
  check-format:
    description: "Run format check"
    default: 'true'
    required: false
  check-deps-audit:
    description: "Run deps.audit"
    default: 'true'
    required: false
  check-deps-unused:
    description: "mix deps.unlock --check-unused"
    default: 'true'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Elixir Project
      uses: myriad-sas/.github/.github/actions/elixir-setup@hub-security
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        ssh-key: ${{ inputs.ssh-key }}
        build-deps: 'false'
        build-app: 'false'
      env:
        MIX_ENV: dev
    
    - name: Check format
      run: mix format --check-formatted
      shell: sh
      if: ${{ inputs.check-format }} == 'true'
    
    - name: Check deps audit
      run: mix deps.audit
      shell: sh
      if: ${{ inputs.check-deps-audit }} == 'true'
    
    - name: Check unused deps
      run: mix deps.unlock --check-unused
      shell: sh
      if: ${{ inputs.check-deps-unused }} == 'true'
