name: "Setup Elixir"
description: setup Elixir + ssh + get deps + compile

inputs:
  # -- Elixir & Erlang version -- #
  elixir:
    description: Which Elixir version to use for the CI
    default: "1.8.0"
    required: false
  otp:
    description: Which OTP version to use for the CI
    default: "21"
    required: false
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  known_hosts:
    description: known_hosts to use for the CI
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh-key }}
        name: id_rsa # optional
        known_hosts: ${{ inputs.known_hosts }}

    - name: fetch elixir dependencies
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{inputs.otp}}
        elixir-version: ${{inputs.elixir}}

    - name: Install hex and rebar
      run: | 
        mix local.hex --force 
        mix local.rebar --force
      shell: bash

    - name: Install dependencies
      run: mix deps.get
      shell: bash

    - name: Compile project
      run: mix compile
      shell: bash

        
        
