name: Run Elixir Project
description: Checks out the code and runs the test
inputs:
  ssh-key:
    description: SSH key to use for the CI
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v4
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ github.event.repository.name }}:1.0
        context: .
        push: false
        cache-from: type=registry,ref=user/${{ github.event.repository.name }}:latest
