name: "Package helm release and publish to s3"
description: set the chart file with the new image and generate the chart.tgz file and push to s3 bucket

inputs:
  url:
    description: "aws s3 bucket endpoint"
    required: true
  username:
    description: "AWS ACCESS_KEY"
    required: true
  password:
    description: "AWS ACCESS_SECRET_KEY"
    required: true
  version:
    description: "The tag of the image / app version + hash commit"
    required: true
  app:
    description: "The sub folder where the chart is stored / name of the application"
    required: true


runs:
  # allow you to bundle multiple workflow steps into a single action, combining multiple run commands into a single reusable action.
  using: "composite"
  steps:
    - name: Install helm
      shell: bash
      run: |
        helm_version="3.10.1"
        tar_filename="helm-v${helm_version}-linux-amd64.tar.gz"
        checksum_filename="helm-v${helm_version}-linux-amd64.tar.gz.sha256sum"
        curl -sSL https://get.helm.sh/${tar_filename} -O
        curl -sSL https://get.helm.sh/${checksum_filename} -O
        cat ${checksum_filename} | sha256sum -c
        
        tar xzf ${tar_filename}
        sudo mv linux-amd64/helm /usr/local/bin/helm
        rm -rf linux-amd64 ${tar_filename} ${checksum_filename}

    - name: Install helm-s3 plugin
      shell: bash
      run: |
        version="${GITHUB_SHA}"
        export HELM_S3_PLUGIN_NO_INSTALL_HOOK=true
        if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
          version="${GITHUB_REF_NAME#v*}"
          export HELM_S3_PLUGIN_NO_INSTALL_HOOK=
        fi
        echo "Check installation of version ${version}"
        helm plugin install https://github.com/hypnoglow/helm-s3.git --version ${version}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.username }}
        aws-secret-access-key: ${{ inputs.password }}
        aws-region: eu-west-3
   
    - name: Release and Publish on s3
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        S3_URL: ${{ inputs.url }}
        APPNAME: ${{ inputs.app }}
      working-directory: ${{ inputs.app }}
      run: |
        helm lint .
        helm package --app-version=$VERSION --version=$VERSION .
        helm s3 init s3://$S3_URL/$APPNAME
        helm s3 push ./$APPNAME-$VERSION.tgz 
    
