name: "Lint Elixir projects"
description:  Check credo

inputs:
  # -- Run steps -- #
  run-credo:
    description: Run Credo
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Credo
      run: mix credo
      shell: bash
      if: inputs.run-credo != 'false'
