name: "Push docker image"
description: push docker image

inputs:
  # -- Docker image -- #
  image:
    description: "Name of the image"
    required: true
  version:
    description: "How to tag the image"
    required: true
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  # -- Docker registry -- #
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-token:
    description: Docker Hub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp
      
    - name: Load image
      run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      shell: bash

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .
        push: true
        tags: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
