name: "Build the docker image, scan it and push it"
description:  build docker image, scan it and push it

inputs:
  # -- Run steps -- #
  run-scan:
    description: Run scan
    default: "true"
  # -- Docker image -- #
  image:
    description: "Name of the image"
    required: true
  version:
    description: "How to tag the image"
    required: true
  # -- SSH key -- #
  ssh-key:
    description: SSH key to use for the CI
    required: true
  # -- Docker registry -- #
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-token:
    description: Docker Hub token
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }} 

    - name: Build image
      uses: docker/build-push-action@v4
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        context: .
        load: true

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      #if: inputs.run-scan != 'false'

    - name: echo
      run: echo "Scan completed"
      shell: bash

    - name: Push image
      uses: docker/build-push-action@v4
      with:
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ inputs.dockerhub-username }}/${{ inputs.image }}:${{ inputs.version }}
        context: .
        push: true