name: start-runner

on: 
  workflow_call:
    inputs:
      config-path:
        description: >-
          path to the ec2.yml file which stores the variables for the instance
        required: true
        type: string
      image-tag:
        description: >-
          tag of the image, for the moment only can pass one tag to the following jobs;
          this is useful when the tag is not 'latest'
        required: false
        type: string
      APP_NAME:
        description: >-
          tag of the image, for the moment only can pass one tag to the following jobs;
          this is useful when the tag is not 'latest'
        required: true
        default: ${{ github.event.repository.name }}
        type: string
      APP_VSN:
        description: >-
          tag of the image, for the moment only can pass one tag to the following jobs;
          this is useful when the tag is not 'latest'
        required: false
        type: string
    outputs:
      uri:
        description: >-
          Uri of the pushed container
          The label is used in two cases:
          - to use as the input of 'image' property for the following jobs;
          - to remove the container from registry when it is not needed anymore.
        value: ${{ jobs.build-n-push.outputs.uri }}

        
jobs:          
  build-n-push:
    name: build & push
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
    outputs:
      uri: ${{ steps.export.outputs.uri }}
      image-tag: ${{ steps.export.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v2
      - name: set up Docker Buildx # docker build action
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: login to ecr
        id: login-ecr
        uses: myriad-actions/login-ecr@main
        with:
          config-path: ${{ inputs.config-path }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          build-args: |
            APP_NAME=${{ inputs.APP_NAME }}
            APP_VSN=${{ inputs.APP_VSN }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.APP_NAME }}:${{ inputs.image-tag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.APP_NAME }}:latest
      - name: export outputs
        id: export
        run: |
          echo "::set-output name=uri::'${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}'"
