name: cd-ecs

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      environment:
        description: >-
          one of the testing, preprod or prod environment, for the workflow run
        required: true
        type: string
      runner:
        description: >-
          runner label on which this workflow will be run
        required: true
        type: string
      task_name:
        description: >
          ecs task name
        required: true
        type: string
      container_name:
        description: >
          ecs task container name
        default: ''
        required: true
        type: string
      image:
        description: >
          image registry name for actions
        default: ''
        required: true
        type: string
      image_name:
        description: >
          fully qualified image registry name for Hub application
        default: ''
        required: true
        type: string
      cluster_name:
        description: >
          ecs cluster name
        default: ''
        required: true
        type: string
      ecs_service_name:
        description: >
          ecs service name
        default: ''
        required: true
        type: string
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string

jobs:
  init_cd_ecs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      RELEASE:  ${{ steps.vars.outputs.RELEASE }}
      IMAGE: ${{ steps.vars.outputs.IMAGE }}
      IS_PREPROD_FROZEN: ${{ steps.status.outputs.IS_PREPROD_FROZEN }}
      IS_PROD_FROZEN: ${{ steps.status.outputs.IS_PROD_FROZEN }}
      RUNNER: ghr-aws
    steps:
      - name: init job
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: set vars
        id: vars
        run: |
          ${{ contains(github.ref_name, env.RELEASE-TAG-PREFIX)  }}  &&  echo "RELEASE=true" >> $GITHUB_OUTPUT  || echo "not a release"
          echo "IMAGE=${{ env.DOCKER-RUNNER-IMAGE }}" >> $GITHUB_OUTPUT
        shell: bash
      - name: get freeze status
        id: status
        uses: myriad-actions/get-deployment-freeze-status@main
        with:
          github-pat:  ${{ secrets.github-pat }}
      - name: approval annotation
        run: |
          echo "::notice title=preprod status:: ${{ steps.status.outputs.IS_PREPROD_FROZEN }}"
          echo "::notice title=prod status:: ${{ steps.status.outputs.IS_PROD_FROZEN }}"
          echo "::notice title=ref:: ${{ github.ref_name }}"
    # - name: preprod approval annotation
    #   if: steps.status.outputs.IS_PREPROD_FROZEN == 'unfrozen'
    #   run: |
    #     echo "::notice title=PREPROD DEPLOYEMENT> An issue will be created in the Issues tab::The timeout minutes of this issues is set to 20 minutes, after which the workflow will continue without deployment. It is possible to re-run the preprod and only the preprod deployment by clicking on the preprod deploy job in the jobs panel, then on the re-run button right beside. The button is visible only after the whole workflow is finished or cancelled, regardless of the outcome"
      - name: prod approval annotation
        if: steps.status.outputs.IS_PROD_FROZEN == 'unfrozen'
        run: |
          echo "::notice title=PROD DEPLOYEMENT> An issue will be created in the Issues tab::The timeout minutes of this issues is set to 5 minutes, after which the workflow will continue without deployment. It is possible to re-run the prod by clicking on the deploy/init_hub_ecs job in the jobs panel, then on the re-run button. The button is visible only after the whole workflow is finished or cancelled, regardless of the outcome"


  deploy_cd_ecs:
    name: deploy_cd_ecs
    needs: init_cd_ecs
    runs-on:  ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
      packages: read
      issues: write
    container:
      image: ${{ inputs.image }}
    outputs:
      continue:  ${{ steps.check-continue.outputs.continue }}
    steps:
      - name: init container
        uses: myriad-actions/init-container@main
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
    # - name: request approval preprod
    #   uses: trstringer/manual-approval@v1
    #   if: inputs.environment == 'preprod'
    #   id: approval-preprod
    #   timeout-minutes: 20
    #   with:
    #     secret: ${{ secrets.GITHUB_TOKEN }}
    #     approvers: ${{ env.PREPROD-APPROVERS }}
    #     minimum-approvals: 1
    #     issue-title: "Release for ${{ inputs.environment }} requested by ${{ github.actor }}"
    #   continue-on-error: true
      - name: request approval prod
        uses: trstringer/manual-approval@v1
        if: inputs.environment == 'prod'
        id: approval-prod
        timeout-minutes: 5
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ env.PROD-APPROVERS }}
          minimum-approvals: 1
          issue-title: "Release for ${{ inputs.environment }} requested by ${{ github.actor }}"
        continue-on-error: true
      - name: check continue
        id: check-continue
        if: ${{ inputs.environment == 'preprod' || inputs.environment == 'prod' }}
        run: |
          ${{ steps.approval-prod.outcome == 'failure' }} && echo "continue=false" >> $GITHUB_OUTPUT || echo "continue=true" >> $GITHUB_OUTPUT
      - name: checkout configurations
        uses: actions/checkout@v3
        with:
          repository:  ${{ env.CI-CONFIG-REPO }}
          token: ${{ secrets.github-pat }}
          path: ${{ env.CI-CONFIG-FOLDER-NAME }}
      - name: deploy
        uses: myriad-actions/deploy@main
        if: steps.check-continue.outputs.continue != 'false'
        with:
          task_name: ${{ inputs.task_name }}
          container_name: ${{ inputs.container_name }}
          image_name: ${{ inputs.image_name }}
          cluster_name: ${{ inputs.cluster_name }}
          ecs_service_name: ${{ inputs.ecs_service_name }}
          config-path: "./main/.github/ecr.json"
      - name: freeze prod
        uses: myriad-actions/set-deployment-freeze-status@main
        if: inputs.environment == 'prod' && steps.check-continue.outputs.continue != 'false'
        with:
          environment: prod
          github-pat:  ${{ secrets.github-pat }}
          status: frozen

  validate:
    name: validate
    needs: deploy_cd_ecs
    if: needs.deploy_cd_ecs.outputs.continue != 'false'
    runs-on:  ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
      packages: read
    container:
      image: ${{ inputs.image }}
    steps:
      - name: init container
        uses: myriad-actions/init-container@main
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: init cache
        uses: actions/cache@v3
        with:
          path: main/${{ env.ARTIFACTS-SRC-PATH }}
          key: ${{ github.sha }}
      - name: validate installed version
        uses: myriad-actions/run@main
        with:
          script: ${{ env.SCRIPT42 }} 
          args: ${{ inputs.environment }}
