name: cd

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      environment:
        description: >-
          one of the testing, preprod or prod envinronment, for the workflow run
        required: true
        type: string
      runner:
        description: >-
          runner label on which this workflow will be ran
        required: true
        type: string
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string
      skip-check:
        description: >-
          whether to skip the check
        default: false
        required: false
        type: string

jobs:
  deploy:
    name: deploy
    runs-on:  ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: download artifacts
        uses: myriad-actions/run@main
        with:
          script: ${{ env.SCRIPT2 }}
          args: testing
      - name: deploy
        uses: myriad-actions/run@main
        with:
          script: ${{ env.LANG }}/${{ env.SCRIPT3 }} 
          args: ${{ inputs.environment }}
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/
          retention-days: 1


  validate:
    name: validate
    needs:
      - deploy
    runs-on:  ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
      - name: validate installed version
        uses: myriad-actions/run@main
        with:
          script: ${{ env.SCRIPT4 }} 
          args: ${{ inputs.environment }}
      - name: set next-env as preprod
        if: inputs.environment == 'testing'
        run: echo 'NEXT-ENV=preprod' >> $GITHUB_ENV
      - name: set next-env as prod
        if: inputs.environment == 'preprod'
        run: echo 'NEXT-ENV=prod' >> $GITHUB_ENV
      - name: tag next env
        uses: myriad-actions/run@main
        if: inputs.environment != 'prod'
        with:
          script: ${{ env.SCRIPT5 }}
          args: ${{ env.NEXT-ENV }}
