name: cd

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      environment:
        description: >-
          one of the testing, preprod or prod envinronment, for the workflow run
        required: true
        type: string
      runner:
        description: >-
          runner label on which this workflow will be ran
        required: true
        type: string
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string

jobs:
  check-freeze:
    name: check freeze
    runs-on: ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: myriad-actions/check-deployment-freeze@bis
        with:
          github-pat: ${{ secrets.github-pat }}
          environment: ${{ inputs.environment }}
  deploy:
    name: deploy
    needs:
      - check-freeze
    runs-on: ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: download artifacts
        uses: myriad-actions/run-ci-scripts@bis
        with:
          script: ${{ env.SCRIPT2 }}
          args: testing
      - name: deploy on testbed
        uses: myriad-actions/run-ci-scripts@bis
        with:
          script: ${{ env.SCRIPT3 }} 
          args: ${{ inputs.environment }}
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/
          retention-days: 1
