name: cd

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      environment:
        description: >-
          one of the testing, preprod or prod envinronment, for the workflow run
        required: true
        type: string
      runner:
        description: >-
          runner label on which this workflow will be ran
        required: true
        type: string
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string

jobs:
  check-freeze:
    name: check freeze
    runs-on: ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: myriad-actions/check-deployment-freeze@bis
        with:
          github-pat: ${{ secrets.github-pat }}
          environment: ${{ inputs.environment }}
