name: check-deploy-validate

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      environment:
        description: >-
          one of the testing, preprod or prod envinronment, for the workflow run
        required: true
        type: string
      runner:
        description: >-
          runner label on which this workflow will be ran
        required: true
        type: string
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string

jobs:
  init-vars:
    name: init variables
    runs-on: ${{ inputs.runner }}
    steps:
      - name: load non-prod launch config
        if: ${{  inputs.environment == 'testing' }} && ${{  env.HOST_MODE == 'ecs' }}
        run: |
          echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-TESTING }}" >> $GITHUB_ENV
      - name: load prod launch config
        if: ${{  inputs.environment == 'preprod' }}  && ${{  env.HOST_MODE == 'ecs' }}
        run: |
          echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-PREPROD }}" >> $GITHUB_ENV
      - name: load prod launch config
        if: ${{  inputs.environment == 'prod' }}  && ${{  env.HOST_MODE == 'ecs' }}
        run: |
          echo "CLUSTER=${{ env.AWS-ECS-CLUSTER-NAME-PROD }}" >> $GITHUB_ENV

  check-freeze:
    name: check freeze
    needs: init-vars
    runs-on: ${{ inputs.runner }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: myriad-actions/check-deployment-freeze@bis
        with:
          cluster: ${{ env.cluster }}
