name: ci

env:
  CI_COMMIT_SHA: ${{ github.sha }}

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
      github-pak:
        description: >-
          GitHub personal access key
        required: false
    inputs:
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string
      runner:
        description: >-
          runner label on which this workflow will be ran
        required: true
        type: string
      image:
        description: >-
          docker image url 
        required: true
        type: string
      mysql-version:
        description: >-
          mysql service container version
        required: false
        default: latest
        type: string
      redis-version:
        description: >-
          redis service container version 
        required: false
        default: latest
        type: string
      influxdb-version:
        description: >-
          influxdb service container version 
        required: false
        default: latest
        type: string
    outputs:
      runner:
        description: >-
          pass runner label to cd workflow
        value: ${{ jobs.build.outputs.runner }}

jobs:
  check:
    name: check
    runs-on:  ubuntu-latest
    outputs:
      continue:  ${{ steps.check-continue.outputs.continue }}
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: init cache
        id: cache
        uses: actions/cache@v3
        with:
          path: main/${{ env.ARTIFACTS-SRC-PATH }}
          key: ${{ github.sha }}
      - name: check continue
        id: check-continue
        run: |
          ${{ steps.cache.outputs.cache-hit  == 'true'  }} && echo "ARTIFACTS=$(cat main/artifacts/head.txt)" >> $GITHUB_ENV || echo "continue"
          ${{  steps.cache.outputs.cache-hit  == 'true' && env.ARTIFACTS == '' }} && "continue=true" >> $GITHUB_OUTPUT || echo "continue=false" >> $GITHUB_OUTPUT 
      - name: annotation
        if: steps.check-continue.outputs.continue == 'false'
        run: |
          echo "::notice title=BUILD SKIPPED>cache found, will skip the build process"

          
  build:
    name: build
    needs:
      - check
    if: needs.check.outputs.continue == 'true'
    runs-on:  
      group: default
    permissions:
      id-token: write
      contents: read
      packages: read
    container:
      image: ghcr.io/myriad-sas/${{ inputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      runner: ${{ steps.set-runner.outputs.label }}
    services: 
      mysql:
        image: mysql:${{ inputs.mysql-version }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
      redis:
        image: redis:${{ inputs.redis-version }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      influxdb:
        image: influxdb:${{ inputs.influxdb-version }}
        options: >-
          --health-cmd "curl -f http://localhost:8086/ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: init container
        uses: myriad-actions/init-container@main
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: extras
        id: set-runner
        run: |
          mkdir -p /root/logs
          echo label=${{ inputs.runner }} >> $GITHUB_OUTPUT 
      - name: init cache
        id: cache
        uses: actions/cache@v3
        with:
          path: main/${{ env.ARTIFACTS-SRC-PATH }}
          key: ${{ github.sha }}
      - name: check build exists
        id: check
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "ARTIFACTS=$(cat main/artifacts/head.txt)" >> $GITHUB_ENV
          ${{ env.ARTIFACTS == '' }} && "SKIP-BUILD=false" >> $GITHUB_OUTPUT || echo "SKIP-BUILD=true" >> $GITHUB_OUTPUT 
      - name: check ssh key
        run: ${{ secrets.github-pak != '' }} && echo "CONFIGURE_SSH=true" >> $GITHUB_ENV || continue 
      - name: configure git ssh
        uses: webfactory/ssh-agent@v0.5.4
        if: env.CONFIGURE_SSH == 'true'
        with:
            ssh-private-key: ${{ secrets.github-pak }}
      - name: build and test
        uses: myriad-actions/run@main
        if: steps.check.outputs.SKIP-BUILD != 'true'
        with:
          script: ${{ env.LANG }}/${{ env.SCRIPT0 }}
      - name: upload build artifacts
        uses: myriad-actions/run@main
        if: steps.check.outputs.SKIP-BUILD != 'true' 
        with:
          script: ${{ env.SCRIPT1 }}
