name: ci

env:
  CI_COMMIT_SHA: ${{ github.sha }}

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
      github-pak:
        description: >-
          GitHub personal access key
        required: false
    inputs:
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string
      runner:
        description: >-
          runner label on which this workflow will be ran
        required: true
        type: string
      image:
        description: >-
          docker image url 
        required: true
        type: string
    outputs:
      runner:
        description: >-
          pass runner label to cd workflow
        value: ${{ jobs.build.outputs.runner }}

jobs:      
  build:
    name: build
    runs-on:  
      group: default
    permissions:
      id-token: write
      contents: read
      packages: read
    container:
      image: ghcr.io/myriad-sas/${{ inputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      runner: ${{ steps.set-runner.outputs.label }}
    steps:
      - name: init container
        uses: myriad-actions/init-container@main
      - name: init job  
        uses: myriad-actions/init-job-debian@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: init cache
        id: cache
        uses: actions/cache@v3
        with:
          path: main/${{ env.ARTIFACTS-SRC-PATH }}
          key: ${{ github.sha }}
      - name: check continue
        if: steps.cache.outputs.cache-hit  == 'true'
        id: check
        run: |
          echo "::notice title=Cache:: found cache, head: $(cat main/artifacts/head.txt)"
          echo "continue=false" >> $GITHUB_OUTPUT 
      - name: extras
        id: set-runner
        if: steps.check.outputs.continue  != 'false'
        run: |
          mkdir -p /root/logs
          echo label=${{ inputs.runner }} >> $GITHUB_OUTPUT 
      - name: check ssh key
        if: steps.check.outputs.continue  != 'false' 
        run: ${{ secrets.github-pak != '' }} && echo "CONFIGURE_SSH=true" >> $GITHUB_ENV || continue 
      - name: configure git ssh
        uses: webfactory/ssh-agent@v0.5.4
        if: env.CONFIGURE_SSH == 'true' && steps.check.outputs.continue  != 'false'
        with:
            ssh-private-key: ${{ secrets.github-pak }}
      - name: build and test
        uses: myriad-actions/run@main
        if: steps.check.outputs.continue  != 'false'
        with:
          script: ${{ env.LANG }}/${{ env.SCRIPT01 }}
      - name: upload build artifacts
        uses: myriad-actions/run@main
        if: steps.check.outputs.continue  != 'false'
        with:
          script: ${{ env.SCRIPT1 }}
