name: deploy-on-ecs

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true

    inputs:
      env-path:
        description: >-
          path to the file for the environment variables
        required: false
        default: ./.github/.env
        type: string

jobs:
  init-vars:
   runs-on: ubuntu-latest
   outputs:
     MYSQL-VERSION: ${{ steps.vars.outputs.MYSQL-VERSION }}
     REDIS-VERSION: ${{ steps.vars.outputs.REDIS-VERSION }}
     INFLUXDB-VERSION: ${{ steps.vars.outputs.INFLUXDB-VERSION }}
     IMAGE: ${{ steps.vars.outputs.DOCKER-RUNNER-IMAGE }}
   steps:
     - name: init job  
       uses: myriad-actions/init-job@main
       with:
         github-pat: ${{ secrets.github-pat }}
         env-path: ${{ inputs.env-path }}
     - name: set vars
       id: vars
       run: |
         echo "::set-output name=MYSQL-VERSION::${{ env.MYSQL-VERSION }}"
         echo "::set-output name=REDIS-VERSION::${{ env.REDIS-VERSION }}"
         echo "::set-output name=INFLUXDB-VERSION::${{ env.INFLUXDB-VERSION }}"
         echo "::set-output name=IMAGE::${{ env.DOCKER-RUNNER-IMAGE }}"

  start-runner:
    uses: ./.github/workflows/start-runner.yml
    secrets:
      github-pat: ${{ inputs.github-pat }}
    with:
      environment: non-prod
      env-path: ${{ inputs.env-path }}

  build-and-test:
    uses: ./.github/workflows/build-in-docker.yml
    needs: init-vars
    secrets:
      github-pat: ${{ inputs.github-pat }}
    with:
      image: ${{ needs.init-vars.output.IMAGE }}
      mysql-version: ${{ needs.init-vars.output.MYSQL-VERSION }}
      redis-version: ${{ needs.init-vars.output.REDIS-VERSION }}
      influxdb-version: ${{ needs.init-vars.output.INFLUXDB-VERSION }}
      env-path: ${{ inputs.env-path }}
      
  stop-runner:
    needs:
      - start-runner
    if: ${{ always() }} 
    uses: ./.github/workflows/stop-runner.yml
    secrets:
      github-pat: ${{ inputs.github-pat }}
    with:
      label: ${{ needs.start-runner.outputs.label }}
      ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
      env-path: ${{ inputs.env-path }}
