name: Hub Covid Pipeline

on:
  workflow_call:
    secrets:
      # -- SSH key -- #
      ssh-key:
        description: SSH key to use for the CI
        required: true

permissions:
  contents: read
  
jobs:
  # setup:
  #   name: Setup Elixir
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: Elixir Setup
  #       uses: myriad-sas/.github/.github/actions/elixir-setup@feature/refactor-workflow
  #       with: 
  #         elixir-version: '1.14.3'
  #         otp-version: '25.2.2'
  #         ssh-key:  ${{ secrets.ssh-key }}
  #         known_hosts: github.com

  # lint:
  #   name: Lint code
  #   runs-on: ubuntu-latest
  #   needs: setup

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Elixir Project
  #       uses: myriad-sas/.github/.github/actions/elixir-setup@feature/refactor-workflow
  #       with: 
  #         elixir-version: '1.14.3'
  #         otp-version: '25.2.2'
  #         ssh-key:  ${{ secrets.ssh-key }}
  #         known_hosts: github.com

  #     - name: Elixir Lint
  #       uses: myriad-sas/.github/.github/actions/elixir-lint@feature/refactor-workflow

  # security:
  #   name: Security checks
  #   runs-on: ubuntu-latest
  #   needs: setup

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Elixir Project
  #       uses: myriad-sas/.github/.github/actions/elixir-setup@feature/refactor-workflow
  #       with: 
  #         elixir-version: '1.14.3'
  #         otp-version: '25.2.2'
  #         ssh-key:  ${{ secrets.ssh-key }}
  #         known_hosts: github.com

  #     - name: Elixir Security
  #       uses: myriad-sas/.github/.github/actions/elixir-security@feature/refactor-workflow

  # test:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   needs: setup
    
  #   services:
  #     # Label used to access the service container
  #     redis:
  #       # Docker Hub image
  #       image: redis:latest
    
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Elixir Project
  #       uses: myriad-sas/.github/.github/actions/elixir-setup@feature/refactor-workflow
  #       with: 
  #         elixir-version: '1.14.3'
  #         otp-version: '25.2.2'
  #         ssh-key:  ${{ secrets.ssh-key }}
  #         known_hosts: github.com

  #     - name: Elixir Test
  #       uses: myriad-sas/.github/.github/actions/elixir-test@feature/refactor-workflow

  docker:
    name: Build & Scan Docker image
    runs-on: ubuntu-latest
    #needs: setup

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        uses: myriad-sas/.github/.github/actions/docker-build-scan@feature/refactor-workflow
        with:
          image: 'hub-covid'
          tag: '1.0'
          ssh-key: ${{ secrets.ssh-key }}
          known_hosts: github.com