name: Hub Covid Pipeline


on:
  workflow_call:
    inputs:
      ssh_key:
        description: SSH key to use for the CI
        required: true
        type: string
            
permissions:
  contents: read
  
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      
      - name: Elixir CI
        uses: myriad-sas/.github/.github/actions/elixir-ci@feature/refactor-workflow
        with: 
          elixir: '1.14.3'
          otp: '25.2.2'
          ssh_key:  ${{ inputs.ssh_key }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

