name: Hub Covid Pipeline


on:
  workflow_call:
    secrets:
      # -- SSH key -- #
      ssh-key:
        description: SSH key to use for the CI
        required: true

permissions:
  contents: read
  
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      
      - name: Elixir Setup
        uses: myriad-sas/.github/.github/actions/elixir-setup@feature/refactor-workflow
        with: 
          elixir-version: '1.14.3'
          otp-version: '25.2.2'
          ssh-key:  ${{ secrets.ssh-key }}
          known_hosts: github.com

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with: 
          elixir-version: '1.14.3'
          otp-version: '25.2.2'
          ssh-key:  ${{ secrets.ssh-key }}
          known_hosts: github.com

      - name: Elixir Lint
        uses: myriad-sas/.github/.github/actions/elixir-lint@feature/refactor-workflow

  security:
    name: security
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with: 
          elixir-version: '1.14.3'
          otp-version: '25.2.2'
          ssh-key:  ${{ secrets.ssh-key }}
          known_hosts: github.com

      - name: Elixir Security
        uses: myriad-sas/.github/.github/actions/elixir-security@feature/refactor-workflow

  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:latest
    
    steps:
      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with: 
          elixir-version: '1.14.3'
          otp-version: '25.2.2'
          ssh-key:  ${{ secrets.ssh-key }}
          known_hosts: github.com

      - name: Elixir Test
        uses: myriad-sas/.github/.github/actions/elixir-test@feature/refactor-workflow