name: hub
on:
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
      github-pak:
        description: >-
          GitHub personal access key
        required: false
    inputs:
      env-path:
        description: >-
          path to the file for the environment variables
        required: false
        default: ./.github/.env
        type: string

jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      RELEASE:  ${{ steps.vars.outputs.RELEASE }}
      IMAGE: ${{ steps.vars.outputs.IMAGE }}
      IS_PREPROD_FROZEN: ${{ steps.status.outputs.IS_PREPROD_FROZEN }}
      IS_PROD_FROZEN: ${{ steps.status.outputs.IS_PROD_FROZEN }}
      RUNNER: ghr-aws
    steps:
      - name: init job
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
          env-path: ${{ inputs.env-path }}
      - name: set vars
        id: vars
        run: |
          ${{ contains(github.ref_name, env.RELEASE-TAG-PREFIX)  }}  &&  echo "RELEASE=true" >> $GITHUB_OUTPUT  || echo "not a release"
          echo "IMAGE=${{ env.DOCKER-RUNNER-IMAGE }}" >> $GITHUB_OUTPUT
          echo "::notice title=ref:: ${{ github.ref_name }}"
        shell: bash

  ci:
    uses: ./.github/workflows/ci.yml
    needs:
      - init
    secrets:
      github-pat: ${{ secrets.github-pat }}
      github-pak: ${{ secrets.github-pak }}
    with:
      image: ${{ needs.init.outputs.IMAGE }}
      env-path: ${{ inputs.env-path }}
      runner: ${{ needs.init.outputs.RUNNER }}

  a-test:
    uses: ./.github/workflows/cd.yml
    needs:
      - init
      - ci
    if: needs.init.outputs.RELEASE !=  'true'
    secrets:
      github-pat: ${{ secrets.github-pat }}
    with:
      environment: testing
      runner: ${{ needs.init.outputs.RUNNER }}
      image: ${{ needs.init.outputs.IMAGE }}


  b-prep:
    uses: ./.github/workflows/cd.yml
    needs:
      - init
      - ci
    if: needs.init.outputs.RELEASE != 'true'
    secrets:
      github-pat: ${{ secrets.github-pat }}
    with:
      environment: preprod
      runner: ${{ needs.init.outputs.RUNNER }}
      image: ${{ needs.init.outputs.IMAGE }}


  c-prod:
    uses: ./.github/workflows/cd.yml
    needs:
      - init
      - ci
    if: github.ref_name == 'master' || github.ref_name == 'DH-*'
    secrets:
      github-pat: ${{ secrets.github-pat }}
    with:
      environment: prod
      runner: ${{ needs.init.outputs.RUNNER }}
      image: ${{ needs.init.outputs.IMAGE }}
