name: start-runner

on: 
  workflow_call:
    secrets:
      github-token:
        description: >-
          GitHub personal access token
        required: true
      runner-ssh-key:
        description: >-
          public key for ssh access to the runner, for troubleshooting purpose
        required: true
    inputs:
      config-path:
        description: >-
          path to the ec2.yml file which stores the variables for the instance
        required: true
        type: string
      env-path:
        description: >-
          path to the .env file which stores the envinronment variables for the instance
        required: true
        type: string
      tools-repository:
        description: >-
          path to the .env file which stores the envinronment variables for the instance
        required: true
        type: string
      tools-folder:
        description: >-
          path to the .env file which stores the envinronment variables for the instance
        required: true
        type: string
      tools-path:
        description: >-
          path to the .env file which stores the envinronment variables for the instance
        required: true
        type: string
    outputs:
      label:
        description: >-
          Name of the unique label assigned to the runner.
          The label is used in two cases:
          - to use as the input of 'runs-on' property for the following jobs;
          - to remove the runner from GitHub when it is not needed anymore.
        value: ${{ jobs.start-runner.outputs.label }}
      ec2-instance-id:
        description: >-
          EC2 Instance Id of the created runner.
          The id is used to terminate the EC2 instance when the runner is not needed anymore.
        value: ${{ jobs.start-runner.outputs.ec2-instance-id }}

jobs:          
  start-runner:
    name: start runner
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - uses: actions/checkout@v2
      - name: start runner
        id: start-ec2-runner
        uses: myriad-actions/start-runner@v5
        with:
          environment: testing
          config-path: ${{ inputs.config-path }}
          github-token: ${{ secrets.github-token }}
  run-launch-scripts:
    name: run launch scripts
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - uses: myriad-actions/run-launch-scripts@v1
        with:
          github-token: ${{ secrets.github-token }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
          runner-ssh-key: ${{ secrets.runner-ssh-key }}
      - name: initialize build environment
        uses: myriad-actions/checkout-repos@v2
        with:
          tools-repository:  ${{ inputs.tools-repository }}
          tools-token: ${{ secrets.github-token }}
          tools-folder: ${{ inputs.tools-folder }}
          tools-path: ${{ inputs.tools-path }}
      - name: set envinronment variables
        uses: myriad-actions/load-environment-variables@v3
        with:
          env-path:  ${{ inputs.env-path }}
