name: start-runner

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      environment:
        description: >-
          one of the testing, preprod or prod envinronment, for the workflow running
        required: true
        type: string
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string
      init:
        description: >-
          whether to run init script on the new runner 
        required: false
        default: true
        type: string
    outputs:
      label:
        description: >-
          Name of the unique label assigned to the runner.
          The label is used in two cases:
          - to use as the input of 'runs-on' property for the following jobs;
          - to remove the runner from GitHub when it is not needed anymore.
        value: ${{ jobs.launch.outputs.label }}
      ec2-instance-id:
        description: >-
          EC2 Instance Id of the created runner.
          The id is used to terminate the EC2 instance when the runner is not needed anymore.
        value: ${{ jobs.launch.outputs.ec2-instance-id }}

jobs:          
  launch:
    name: launch
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
      - name: load non-prod launch config
        if: "${{  inputs.environment != 'prod' }}"
        run: |
          echo "CONFIG-PATH=$(echo ${{ env.AWS-EC2-RUNNER-NON-PROD-CONFIG }})" >> $GITHUB_ENV
      - name: load prod launch config
        if: "${{  inputs.environment == 'prod' }}"
        run: |
          echo "CONFIG-PATH=$(echo ${{ env.AWS-EC2-RUNNER-PROD-CONFIG }})" >> $GITHUB_ENV
      - name: start runner
        id: start-ec2-runner
        uses: myriad-actions/start-runner@main
        with:
          environment: ${{ inputs.environment }}
          config-path: ${{ env.CONFIG-PATH }}
          github-pat: ${{ secrets.github-pat }}
  init:
    name: init
    needs: launch
    runs-on: ${{ needs.launch.outputs.label }}
    if: ${{ inputs.init == 'true' }}
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
      - name: init runner
        uses: myriad-actions/run-launch-scripts@main
        with:
          runner-ssh-key: ${{ env.AWS-RUNNER-SSH-PUBLIC-KEY }}
