name: stop-runner

on: 
  workflow_call:
    secrets:
      github-pat:
        description: >-
          GitHub personal access token
        required: true
    inputs:
      env-path:
        description: >-
          path to the configuration file of environment variables
        default: ./.github/.env
        required: false
        type: string
      label:
        description: >-
          Name of the unique label assigned to the runner.
          The label is used in two cases:
          - to use as the input of 'runs-on' property for the following jobs;
          - to remove the runner from GitHub when it is not needed anymore.
        required: true
        type: string
      ec2-instance-id:
        description: >-
          EC2 Instance Id of the created runner.
          The id is used to terminate the EC2 instance when the runner is not needed anymore.
        required: true
        type: string
        
jobs:
  terminate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: init job  
        uses: myriad-actions/init-job@main
        with:
          github-pat: ${{ secrets.github-pat }}
      - name: stop on-demande ec2 instance
        uses: myriad-actions/stop-runner@bis
        if: inputs.ec2-instance-id != ''
        with:
          github-pat: ${{ secrets.github-pat }}
          label: ${{ inputs.label }}
          ec2-instance-id: ${{ inputs.ec2-instance-id }}
